### ISSUE TITLE
Converter from WebP to APNG/PNG, without gaps

### ISSUE THREAD

**Issue by acterhd** [Deckromancy/AnimatedEncoder#2]
Hello. I tried to compile libpng 1.6.28, and understand that need special edition of libpng, that never will compatible APNG patch. 

For me generally need converter webp to apng/png, without or less gaps (with dispose methods in 1:1, color space and bits also 1:1, RGBA ia RGBA, RGB is RGB, etc...). I want to write Firefox plug-in that coverage 90% of WebP format.

**Comment by Deckromancy** [comment]
Hello, there.

To make a Firefox plugin using AnimatedEncoder.js that converts WebP to APNG, Firefox would need to be able to extract and draw WebP frames on a canvas.

Firefox does not currently support drawing WebP, but there is a possible workaround. The workaround would be complex, but it is to extract the VP8 stream from each frame of the WebP, wrap it in WebM headers and formatting, load the created single-frame WebM Blob() into a <video> tag, then draw the video on the canvas. (WebP and WebM both use the VP8 bitstream, and Firefox currently only supports WebM.)

If you could get that working you could possibly do it using a technique like this page uses to convert from GIF to APNG:

http://AnimatedPNGs.com/Optimize_and_Convert
The AnimatedDecoder() is created from the GIF being converted. The AnimatedDecoder looks through the frames of the GIF, it extracts the GIF payload, wraps it in the GIF headers to make a Blob() of the frame as a single-frame-image and draws that Blob on the canvas according to the instructions(x,y,width,height) in the Image Descriptor for that frame, and adds the duration based on what is in the Graphic Control Extension(GCE).
After the frame image is added to the AnimatedEncoder() the disposal specified on the GCE is applied to the canvas being drawn on, then the next frame is processed in the same way.
Once all of the frames for the APNG are built, animatedEncoder.saveAnimatedFile() is called to encode those built frames as an Animated PNG.

To do this with WebP to APNG, instead of GIF to APNG,
You could implement WebP decoding in AnimatedDecoder().
You would look at the WebP 'ANMF' chunk instead of Image-Descriptor/GCE.
In WebP, the 'ANMF' chunk for each frame contains the frame 'x', 'y', 'width - 1', 'height - 1', and frame duration.
This data in ANMF is followed by (optionally an 'ALPH' alpha payload chunk) and then always a 'VP8 ' payload chunk.
( https://developers.google.com/speed/webp/docs/riff_container )

APNG stores a numerator and denominator for the duration in the fcTL chunk, while WebP only has an unsigned integer for the number of milliseconds, so you should be able to get the same frame duration.
When converting from WebP to APNG, you could ALWAYS set the denominator to 1000 so that the APNG is also using milliseconds and just set the numerator to what the milliseconds value is set to in the WebP.

Example:
WebP milliseconds in ANMF chunk: 500 (half of a second)
APNG fcTL chunk would have, numerator: 500, denominator: 1000

If there is issues getting the color right, it might help to make sure that if a 'ICCP' color profile chunk is in the source WebP, it is copied into the extracted frames used to draw onto the canvas.

If Firefox supported WebP directly, that complex workaround would not be needed.
Firefox progress of implementing WebP is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1294490

**Comment by acterhd** [comment]
So... need search workaround for compile libpng and libwebp to JS, from WebAssembly possible change webp to png. But I want more, and convert with less gaps, without any data loss, byte in byte.

**Comment by Deckromancy** [comment]
Compiling those to JS is one way to go about it, but note that AnimatedEncoder.js does NOT use libpng or libwebp. AnimatedEncoder draws the image for each frame on the HTML5 <canvas> and then processes the pixels drawn for each frame to build an optimized PNG using the deflate libraries pako and Zopfli.

**Comment by Deckromancy** [comment]
I've given what input I can so I'm closing the issue. Hope you can get that working. Zopfli JS was done with Emscripten, so, yes, that might work for what you want to do...
